### ISSUE TITLE
Furnace status value

### ISSUE THREAD

**Issue by xxtro** [LelandP/heatmaster_homeassistant#2]
The furnace status is not showing a value. I checked the logs and I get this error:

ValueError: Sensor sensor.heatmaster_hassio_furnace_status has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Idle' (<class 'str'>)

Do I need to change the template for this sensor in configuration.yaml?

**Comment by LelandP** [comment]
I think there is a Python issue, I haven't booted up my furnace yet this year to debug the issue. Its likely a change in the Hassio Core that broke this.

**Comment by xxtro** [comment]
I just started mine up for the winter.  Thanks for your work on this. I really like graphing the burn on my furnace.

**Comment by LelandP** [comment]
@xxtro I have pushed an update. It should be working now hopefully.

**Comment by xxtro** [comment]
I'll update and check. Thank you!

**Comment by xxtro** [comment]
Working now. Thank you!
